"""empty message

Revision ID: 7334c9990e71
Revises: bcca95b5ecbf
Create Date: 2019-05-26 23:00:04.674493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7334c9990e71'
down_revision = 'bcca95b5ecbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    # ### end Alembic commands ###
